name: Create release

on:
  workflow_dispatch

jobs:
  create_release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 21
      - name: Set variables
        run: |
          echo "plugin_jar=$(./gradlew printFilename -q | grep 'filename=' | cut -d'=' -f2)" >> $GITHUB_ENV
      - name: Build plugin
        run: ./gradlew build
      - name: Create github release
        # You may pin to the exact commit or the version.
        # uses: softprops/action-gh-release@69320dbe05506a9a39fc8ae11030b214ec2d1f87
        uses: softprops/action-gh-release@v2.0.5
        with:
          tag_name: ${{ env.plugin_version }}
          files: build/libs/${{ env.plugin_jar }}
